const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const path=require('node:path');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage();
 try{
  const consoleErrors=[];
  page.on('console',message=>{if(message.type()==='error')consoleErrors.push(message.text())});
  await page.goto(process.env.DMS_WORKBENCH_URL||'http://127.0.0.1:56811/');
  await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');
  await page.locator('#samples').selectOption('case01');
  assert(await page.locator('#material-library').isVisible(),'left material library workspace is visible');
  assert(await page.getByRole('button',{name:'添加材料'}).isVisible());
  assert(await page.locator('#object-selection').isVisible(),'object selection table is visible');
  const headers=await page.locator('#object-selection thead th').allTextContents();
  assert.equal(headers.includes('状态'),false,'status column is removed from object selection table');
  assert.equal(headers.includes('编辑'),true,'edit column exists in object selection table');
  assert.equal(headers[headers.length-1],'编辑','edit column is the table last column');
  assert.equal(await page.locator('#geometry-preview canvas').count(),1,'09B provides one minimal review preview');
  assert(await page.locator('#package-info').textContent(),'current package information is visible');
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'desktop page has no horizontal overflow');
  assert.equal(await page.locator('.object-ref-short').count(),3,'input references use compact labels');
  assert.equal(await page.locator('.object-select').count(),3,'only three input regions appear as assignable rows');
  assert.equal(await page.locator('#objects tr button', {hasText:'编辑'}).count(),3,'each row exposes an edit button');
  assert(await page.locator('#selection-summary').isVisible(),'selection controls are visible');
  assert(await page.locator('#geometry-view').isVisible(),'geometry view separates input and fused-result modes');
  assert.equal(await page.locator('#other-opacity').count(),0,'manual other-object opacity is replaced by selection defaults');
  const [aRef,gRef,bRef]=await page.locator('#objects tr').evaluateAll(rows=>rows.map(row=>row.dataset.ref));
  const cameraBeforeSelection=await page.locator('#preview-canvas').getAttribute('data-camera');
  await page.locator('.object-select').first().check();
  const aState=await page.locator('#preview-canvas').evaluate(node=>JSON.parse(node.dataset.layerState));
  assert.deepEqual(aState.input_alpha,{[aRef]:.6,[gRef]:.2,[bRef]:.1},'selecting A applies the three-level opacity rule from confirmed package adjacency');
  assert.deepEqual(aState.selected,[aRef]);
  assert.equal(aState.related.patches.length,1,'selecting A shows its one confirmed package patch');
  assert.equal(await page.locator('#preview-canvas').getAttribute('data-camera'),cameraBeforeSelection,'selection keeps camera state');
  const relatedText=await page.locator('#related-interfaces').textContent();
  assert.equal((relatedText||'').includes('patch '),true,'selection summary exposes related confirmed patches');
  await page.locator('.object-select').nth(1).check();
  const agState=await page.locator('#preview-canvas').evaluate(node=>JSON.parse(node.dataset.layerState));
  assert.deepEqual(agState.input_alpha,{[aRef]:.6,[gRef]:.6,[bRef]:.2},'multi-select merges confirmed relationships and keeps the selected inputs at 0.6');
  assert.equal(agState.related.patches.length,2,'multi-select shows both confirmed package patches');
  await page.locator('#clear-selection').click();
  assert.equal(await page.locator('#preview-canvas').getAttribute('data-selection'),'','clear selection restores whole preview');
  assert.equal((await page.locator('#geometry-view option:checked').textContent()).includes('融合结果'),false,'CASE01 has no fused result in the default input view');
  await page.locator('#samples').selectOption('c02');
  await page.waitForFunction(()=>!document.querySelector('#geometry-view option[value="fused_result"]').disabled);
  await page.locator('#geometry-view').selectOption('fused_result');
  assert.equal(await page.locator('#preview-canvas').getAttribute('data-view'),'fused_result','fused geometry is available through its own view mode');
  await page.locator('#samples').selectOption('case01');
  await page.locator('#package-info').filter({hasText:'CASE01'}).waitFor();
  await page.locator('#package-file').setInputFiles(path.join(__dirname,'fixtures','unknown-labels.dmslicer'));
  await page.locator('#package-info').filter({hasText:'Unknown labels'}).waitFor();
  assert.equal(await page.locator('.object-select').count(),3,'a locally imported package exposes only its input objects');
  await page.locator('.object-select').first().check();
  const unknownState=await page.locator('#preview-canvas').evaluate(node=>JSON.parse(node.dataset.layerState));
  assert.equal(unknownState.view,'inputs','unknown stable references stay in input view');
  assert.deepEqual(unknownState.selected,['input:x'],'selected objects are reflected in layer state');
  assert.deepEqual(unknownState.input_alpha,{ 'input:x':.6,'input:y':.2,'input:z':.1},'unknown stable references use package-confirmed adjacency without display-name parsing');
  assert.equal((unknownState.related?.patches||[]).includes('patch:x-y'),true,'unknown stable references include the expected connected patch');
  assert.equal((unknownState.related?.remaining||[]).length,0,'unknown stable references expose no remaining related regions');
  assert.equal(await page.locator('#geometry-view option[value="fused_result"]').evaluate(option=>option.disabled),true,'a package without a fused result explains that the separate view is unavailable');
  await page.locator('#samples').selectOption('case01');
  await page.locator('#package-info').filter({hasText:'CASE01'}).waitFor();
  assert((await page.locator('#package-info').textContent()).includes('CASE01'),'sample selection remains available after an imported package');
  const caseInfoBeforeRejectedImport=await page.locator('#package-info').textContent();
  await page.locator('#package-file').setInputFiles(path.join(__dirname,'fixtures','not-a-result-package.json'));
  await page.locator('#status').filter({hasText:'导入 .dmslicer 包失败'}).waitFor();
  assert.equal(await page.locator('#package-info').textContent(),caseInfoBeforeRejectedImport,'a rejected local file leaves the current package loaded');

  const firstRow=page.locator('#objects tr').first();
  const secondRowMaterial=(await page.locator('#objects tr').nth(1).locator('td').nth(4).textContent())?.trim();
  await firstRow.locator('button', {hasText:'编辑'}).click();
  await page.getByRole('dialog',{name:'编辑材料与语义'}).waitFor();
  await page.locator('#assignment-type').selectOption('Source');
  await page.locator('#assignment-material').selectOption('PLA');
  await page.locator('#apply').click();
  await page.getByRole('dialog',{name:'编辑材料与语义'}).waitFor({state:'hidden'});
  assert.equal((await firstRow.locator('td').nth(4).textContent())?.trim(),'PLA','row edit button updates that row only');
  assert.equal((await page.locator('#objects tr').nth(1).locator('td').nth(4).textContent())?.trim(),secondRowMaterial,'one-row edit leaves the other row material unchanged');

  for(const key of ['c02','u05','s04','pmulti']){
   const previousFirstRef=await page.locator('#objects tr').first().getAttribute('data-ref');
   const packageResponse=page.waitForResponse(response=>response.url().endsWith('/package')&&response.request().method()==='POST');
   await page.locator('#samples').selectOption(key);
   await packageResponse;
   await page.waitForFunction(previous=>document.querySelector('#objects tr')?.dataset.ref!==previous,previousFirstRef);
   const sampleCanvas=page.locator('#preview-canvas'),sampleCamera=await sampleCanvas.getAttribute('data-camera');
   const refs=await page.locator('#objects tr').evaluateAll(rows=>rows.map(row=>row.dataset.ref));
   await page.locator('.object-select').first().check();
   const state=await sampleCanvas.evaluate(node=>JSON.parse(node.dataset.layerState));
   assert.equal(state.input_alpha[refs[0]],.6,key+' keeps the selected input at 0.6');
   assert(Object.values(state.input_alpha).every(alpha=>[.1,.2,.6].includes(alpha)),key+' uses only the documented selection opacity levels');
   assert.equal(await sampleCanvas.getAttribute('data-camera'),sampleCamera,key+' selection does not reset the camera');
   const fused=page.locator('#geometry-view option[value="fused_result"]');
   if(await fused.evaluate(option=>option.disabled)) assert((await fused.textContent()).includes('包内未提供'),key+' explains an absent fused view');
   else {await page.locator('#geometry-view').selectOption('fused_result');assert.equal(await sampleCanvas.getAttribute('data-view'),'fused_result',key+' keeps fused geometry in an independent view');}
   await page.locator('#geometry-view').selectOption('inputs');
  }
  await page.locator('#samples').selectOption('case01');
  await page.locator('#package-info').filter({hasText:'CASE01'}).waitFor();
  const materialsBefore=await page.locator('#library-list .library-row').count();
  await page.locator('#add').click();
  assert(await page.locator('#material-category').isVisible(),'minimal category field is visible');
  assert(await page.locator('#nozzle-mode').isVisible(),'nozzle single/range mode is visible');
  assert(await page.locator('#nozzle-value').isVisible(),'single nozzle temperature is visible by default');
  assert.equal(await page.locator('#nozzle-min').isVisible(),false,'range minimum is hidden in single mode');
  await page.locator('#nozzle-mode').selectOption('range');
  assert.equal(await page.locator('#nozzle-value').isVisible(),false,'single temperature hides in range mode');
  assert(await page.locator('#nozzle-min').isVisible(),'range minimum is visible');
  assert.equal(await page.locator('#material-properties').count(),0,'generic JSON editor is absent');
  await page.getByRole('dialog',{name:'材料属性'}).getByRole('button',{name:'取消'}).click();
  assert.equal(await page.getByRole('dialog',{name:'材料属性'}).isVisible(),false,'empty add dialog cancels without native validation');
  assert.equal(await page.locator('#library-list .library-row').count(),materialsBefore,'cancel keeps material library unchanged');
  await page.locator('.object-select').first().check();
  assert.equal(await page.locator('#reset').isEnabled(),true,'reset button enables after selection exists');
  const canvas=page.locator('#preview-canvas'),before=await canvas.getAttribute('data-camera');
  await canvas.hover();await page.mouse.wheel(0,-180);
  assert.notEqual(await canvas.getAttribute('data-camera'),before,'wheel changes preview camera state');
  await page.locator('#fit-preview').click();
  assert.equal(await canvas.getAttribute('data-camera'),'-0.60,0.45,1.00','Fit resets preview camera state');
  await page.locator('.object-select').first().check();
  await page.getByRole('button',{name:'编辑材料与语义'}).click();
  await page.getByRole('dialog',{name:'编辑材料与语义'}).waitFor();
  await page.locator('#assignment-type').selectOption('Source');
  assert(await page.locator('#assignment-material').isVisible());
  await page.locator('#assignment-material').selectOption('PLA');
  await page.locator('#assignment-type').selectOption('Gradient');
  assert(await page.locator('#assignment-group').isVisible());
  assert(await page.locator('#assignment-material').isDisabled());
  assert.equal(await page.locator('#assignment-material').inputValue(),'');
  await page.locator('#assignment-add').click();
  await page.getByRole('dialog',{name:'材料属性'}).waitFor();
  await page.locator('#material-id').fill('custom-a');
  await page.locator('#material-name').fill('Custom A');
  await page.locator('#material-color').fill('#123456');
  await page.getByRole('button',{name:'保存材料'}).click();
  assert(await page.getByRole('dialog',{name:'编辑材料与语义'}).isVisible());
  assert.equal(await page.locator('#assignment-material').inputValue(),'');
  await page.getByRole('button',{name:'取消'}).click();
  await page.locator('.object-select').first().check();
  assert.equal(await page.locator('#reset').isEnabled(),true,'reset button enables before clear-assignment');
  const caseInfoAfterAssignment=await page.locator('#package-info').textContent();
  await page.getByRole('button',{name:'清除所选分配'}).click();
  await page.getByRole('button',{name:'确认重置'}).click();
  assert.equal(await page.locator('#preview-canvas').isVisible(),true,'model preview remains mounted after clear-assignment');
  assert.equal(await page.locator('#package-info').textContent(),caseInfoAfterAssignment,'package info remains unchanged after clearing assignment');
  assert.deepEqual(consoleErrors.filter(error=>!error.includes('the server responded with a status of 400')),
    [],'selection and view interactions do not emit unexpected console errors');
}finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1});
