"""09B-only material/semantic development preview; no geometry renderer."""
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
import argparse, json
from .geometry_import import load_samples
from .result_package import MAX_UPLOAD, read_package

def handler(samples):
    template=Path(__file__).with_name('material_semantic_preview.html').read_text(encoding='utf-8')
    annotation=Path(__file__).with_name('workspace_annotations.js').read_text(encoding='utf-8')
    page=template.replace('__ANNOTATIONS__',annotation)+"<style>body{overflow-x:hidden}.object-table{table-layout:fixed}.object-table th:nth-child(3),.object-table td:nth-child(3){width:20%}.object-table th:nth-child(2),.object-table td:nth-child(2){width:20%;overflow-wrap:anywhere}.object-table td{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#object-selection{overflow:auto}</style><script>toggle=()=>{let g=$('assignment-type').value;if(g==='Gradient')$('assignment-material').value='';$('assignment-material').disabled=g==='Gradient';$('group-wrap').classList.toggle('hidden',g!=='Gradient')};$('assignment-type').onchange=toggle;const recordedDraw=draw;draw=()=>{recordedDraw();$('preview-canvas').dataset.camera=az.toFixed(2)+','+el.toFixed(2)+','+zoom.toFixed(2)};const rawRows=rows;rows=()=>{rawRows();document.querySelectorAll('#objects tr').forEach(row=>{let cell=row.children[2],full=cell.textContent,short=full.length>18?'…'+full.slice(-16):full,button=document.createElement('button');button.className='object-ref-short';button.textContent=short;button.title='展开完整稳定引用';button.onclick=()=>{button.textContent=button.textContent===short?full:short};cell.replaceChildren(button)})};const materialCancel=$('material').querySelector('button[value=cancel]');materialCancel.type='button';materialCancel.onclick=()=>$('material').close()</script>"
    page += """<script>
const form=$('material').querySelector('form'), oldProps=$('material-properties').closest('label'); oldProps.remove();
const fields=document.createElement('div');fields.innerHTML='<label>材料类别/预设 <select id="material-category"><option value="Custom">Custom</option><option>PLA</option><option>ABS</option><option>PETG</option><option>TPO</option></select></label><fieldset><legend>喷嘴温度（°C，可留空）</legend><label>模式 <select id="nozzle-mode"><option value="single">单值</option><option value="range">范围</option></select></label><input id="nozzle-value" type="number" placeholder="单值"><input id="nozzle-min" type="number" placeholder="最小值"><input id="nozzle-max" type="number" placeholder="最大值"></fieldset><fieldset><legend>热床温度（°C，可留空）</legend><label>模式 <select id="bed-mode"><option value="single">单值</option><option value="range">范围</option></select></label><input id="bed-value" type="number" placeholder="单值"><input id="bed-min" type="number" placeholder="最小值"><input id="bed-max" type="number" placeholder="最大值"></fieldset>';
form.insertBefore(fields,$('material-error'));const libraryActions=document.createElement('p');libraryActions.innerHTML='<button id="export-library" type="button">导出材料库 JSON</button><label>导入材料库 JSON <input id="import-library" type="file" accept=".json"></label><span class="hint">材料库文件与案例 assignment 配置分开保存。</span>';$('material-library').append(libraryActions);
const q=id=>$(id), quantity=(prefix)=>{let mode=q(prefix+'-mode').value,v=q(prefix+'-value').value,min=q(prefix+'-min').value,max=q(prefix+'-max').value;if(mode==='single'&&v==='')return null;if(mode==='range'&&min===''&&max==='')return null;let base={unit:'°C',source:'USER_INPUT',evidence:'USER_INPUT'};return mode==='single'?{...base,value:Number(v)}:{...base,min:Number(min),max:Number(max)}};
q('save-material').onclick=e=>{e.preventDefault();try{let props={},n=quantity('nozzle'),b=quantity('bed');if(n)props.nozzle_temperature=n;if(b)props.bed_temperature=b;WorkspaceAnnotations.putMaterial(w,{id:q('material-id').value.trim(),name:q('material-name').value.trim(),category:q('material-category').value,color:q('material-color').value,description:q('material-description').value,properties:props});q('material').close();q('status').textContent='材料已保存到草稿；尚未导出材料库文件。';q('save').disabled=false;render();if(returnAssignment){materials();q('assignment').showModal()}}catch(x){q('material-error').textContent=x.message}};
window.openMaterial=id=>{returnAssignment=q('assignment').open;selectedMaterial=id||null;let item=id&&w.material_library.materials.find(x=>x.id===id);q('material-id').value=item?.id||'';q('material-id').readOnly=!!item;q('material-name').value=item?.name||'';q('material-category').value=item?.category||'Custom';q('material-color').value=item?.color||'#498b92';q('material-description').value=item?.description||'';for(const prefix of ['nozzle','bed']){let property=item?.properties?.[prefix+'_temperature'];q(prefix+'-mode').value=property?.min===undefined?'single':'range';q(prefix+'-value').value=property?.value??'';q(prefix+'-min').value=property?.min??'';q(prefix+'-max').value=property?.max??'';}q('material-error').textContent='';if(returnAssignment)q('assignment').close();q('material').showModal()};q('add').onclick=()=>openMaterial();q('assignment-add').onclick=()=>openMaterial();materialCancel.onclick=()=>{q('material').close();q('status').textContent='已取消，未保存任何更改。'};
q('export-library').onclick=()=>{let f=WorkspaceAnnotations.exportLibrary(w.material_library,'dmslicer-local-library'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(f,null,2)],{type:'application/json'}));a.download='materials.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);q('status').textContent='已导出材料库 JSON；案例 assignment 需另行 Save。'};
q('import-library').onchange=async e=>{try{let l=WorkspaceAnnotations.importLibrary(await e.target.files[0].text());w.material_library=l;w.material_library_version=l.version;render();q('status').textContent='已导入材料库草稿；未覆盖案例 assignment。'}catch(x){q('status').textContent='材料库导入失败：'+x.message+'；当前库保留。'}finally{e.target.value=''}};
</script>"""
    page += """<style>#material label{margin:6px 0}#material fieldset{display:grid;grid-template-columns:110px 1fr 1fr;gap:6px;margin:8px 0;border:1px solid #d5e0e4;border-radius:5px}#material fieldset legend{font-size:13px}#material-id{font-size:12px;color:#647780}</style><script>
const tempVisibility=prefix=>{const range=q(prefix+'-mode').value==='range';q(prefix+'-value').hidden=range;q(prefix+'-min').hidden=!range;q(prefix+'-max').hidden=!range};for(const prefix of ['nozzle','bed']){q(prefix+'-mode').onchange=()=>tempVisibility(prefix);tempVisibility(prefix)};const idLabel=q('material-id').closest('label');idLabel.childNodes[0].textContent='材料 ID（自动生成，可修改）';q('material-color').style.cssText='width:48px;height:34px;padding:2px;border:1px solid #607780;border-radius:5px;cursor:pointer';[...q('material').querySelectorAll('p')].filter(p=>p.textContent.includes('属性 JSON')).forEach(p=>p.remove());q('material-category').closest('label').previousElementSibling?.insertAdjacentElement('afterend',q('material-category').closest('label'));
</script>"""
    class H(BaseHTTPRequestHandler):
        def reply(self,status,value,mime='application/json'):
            data=value.encode() if isinstance(value,str) else value;self.send_response(status);self.send_header('Content-Type',mime+'; charset=utf-8');self.send_header('Content-Length',str(len(data)));self.send_header('Cache-Control','no-store');self.end_headers();self.wfile.write(data)
        def do_GET(self):
            if self.path=='/':return self.reply(200,page,'text/html')
            if self.path=='/samples':return self.reply(200,json.dumps([{'key':k,'label':v['label']} for k,v in samples.items()]))
            key=self.path.removeprefix('/sample/')
            if self.path.startswith('/sample/') and key in samples:return self.reply(200,samples[key]['path'].read_bytes(),'application/octet-stream')
            return self.reply(404,'{}')
        def do_POST(self):
            try:
                n=int(self.headers.get('Content-Length','0'));assert 0<n<=MAX_UPLOAD;self.reply(200,json.dumps(read_package(self.rfile.read(n))))
            except Exception as e:self.reply(400,json.dumps({'error':str(e)}))
    return H
def main():
    p=argparse.ArgumentParser();p.add_argument('--port',type=int,default=56811);p.add_argument('--samples',type=Path,required=True);a=p.parse_args();s=ThreadingHTTPServer(('127.0.0.1',a.port),handler(load_samples(a.samples)));print(f'09B material/semantic preview: http://127.0.0.1:{a.port}/',flush=True);s.serve_forever()
if __name__=='__main__':main()
